name: ndashboard
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  dynamic_app_icon_flutter_plus: ^1.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
